"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

[directory]
truncate_to_repo = false
truncation_length = 4
truncation_symbol = '.../'
before_repo_root_style = 'bold blue'
repo_root_style = "bold red"
